blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://github.com/2321605193/2321605193.github.io
    about: The issue which is not created via https://github.com/2321605193/2321605193.github.io will be closed immediately.